### ISSUE TITLE
Conflict message.

### ISSUE THREAD

**Issue by tomcat0090** [HavokInspiration/wrench#11]
https://github.com/HavokInspiration/wrench/blob/daf6bd75dd2789b7272e36c8087e84e0238a40ab/src/Mode/View.php#L23-L28

**Comment by HavokInspiration** [comment]
Good catch ! I fixed it in https://github.com/HavokInspiration/wrench/commit/c3e62b34093d7a1f0e64b475807d9082e7deac61 and tagged a new release.

Thanks !
